name: HuaWei

on:
#  push:
#    branches: [ master ]
  schedule:
    - cron: '20 0,2 * * *'

env:
  DING_TOKEN: ${{ secrets.DING_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.6'

    - name: requirements
      run: |
        pip3 install -r requirements.txt

    - name: Run HUAWEI yufei
      run: |
        python3 main.py --client huawei --username ${{ secrets.CAOYUFEI_USERNAME }} --password ${{ secrets.CAOYUFEI_PASSWORD }} --git-url ${{ secrets.CAOYUFEI_GIT }}

    - name: Run HUAWEI hua
      run: |
        python3 main.py --client huawei --username ${{ secrets.HUA_USERNAME }} --password ${{ secrets.HUA_PASSWORD }} --git-url ${{ secrets.HUA_GIT }}
